CACHE MANIFEST
#1787522217
data.js
c2runtime.js
jquery-2.1.1.min.js
offlineClient.js
images/fundo-sheet0.png
images/fundo-sheet1.png
images/fundo-sheet2.png
images/botaotutorial-sheet0.png
images/tutorial-sheet0.png
images/tutorial-sheet1.png
images/tutorial-sheet2.png
images/tutorial-sheet3.png
images/imgdiv1-sheet0.png
images/imgdiv2-sheet0.png
images/imgdiv3-sheet0.png
images/imgdiv4-sheet0.png
images/imgint1-sheet0.png
images/imgint1-sheet1.png
images/imgint3-sheet0.png
images/imgint3-sheet1.png
images/imgint2-sheet0.png
images/imgint2-sheet1.png
images/imgint4-sheet0.png
images/imgint4-sheet1.png
images/imgext4-sheet0.png
images/imgext2-sheet0.png
images/imgext3-sheet0.png
images/direitaext-sheet0.png
images/imgext5-sheet0.png
images/imgext6-sheet0.png
images/imgext7-sheet0.png
images/imgext8-sheet0.png
images/imgint5-sheet0.png
images/imgint5-sheet1.png
images/imgint6-sheet0.png
images/imgint6-sheet1.png
images/imgint7-sheet0.png
images/imgint7-sheet1.png
images/imgint8-sheet0.png
images/imgdiv5-sheet0.png
images/imgdiv6-sheet0.png
images/imgdiv7-sheet0.png
images/imgdiv8-sheet0.png
images/pular-sheet0.png
images/esquerdaext-sheet0.png
images/imgext9-sheet0.png
images/imgext10-sheet0.png
images/imgext11-sheet0.png
images/imgext12-sheet0.png
images/imgint9-sheet0.png
images/imgint10-sheet0.png
images/imgint11-sheet0.png
images/imgint12-sheet0.png
images/imgdiv9-sheet0.png
images/imgdiv10-sheet0.png
images/imgdiv11-sheet0.png
images/imgdiv12-sheet0.png
images/fechar-sheet0.png
images/pintar-sheet0.png
images/fundomodal-sheet0.png
images/painelsup-sheet0.png
images/painelsup-sheet1.png
images/painelsup-sheet2.png
images/painelsup-sheet3.png
images/painelsup-sheet4.png
images/painelsup-sheet5.png
images/painelsup-sheet6.png
images/painelsup-sheet7.png
images/painelesq-sheet0.png
images/painelesq-sheet1.png
images/painelesq-sheet2.png
images/painelesq-sheet3.png
images/comum-sheet0.png
images/pixel-sheet0.png
images/linhas-sheet0.png
images/formas-sheet0.png
images/6star-sheet0.png
images/coracao-sheet0.png
images/5star-sheet0.png
images/penta-sheet0.png
images/4star-sheet0.png
images/circu-sheet0.png
images/quad-sheet0.png
images/trian-sheet0.png
images/imagens-sheet0.png
images/carregar-sheet0.png
images/salvar-sheet0.png
images/gaveta-sheet0.png
images/gaveta-sheet1.png
images/gaveta-sheet2.png
images/tam3-sheet0.png
images/tam5-sheet0.png
images/tam2-sheet0.png
images/tam1-sheet0.png
images/tam4-sheet0.png
images/canvas.png
images/pincel-sheet0.png
images/pincel-sheet1.png
images/pincel-sheet2.png
images/boxborracha-sheet0.png
images/tamanhoformas-sheet0.png
images/tamanhoformas-sheet1.png
images/tamanhoformas-sheet2.png
images/canvaspreview.png
images/fundorgb-sheet0.png
images/mover-sheet0.png
images/aumentar-sheet0.png
images/diminuir-sheet0.png
images/diminuir-sheet1.png
images/camera-sheet0.png
images/borracha-sheet0.png
images/borracha-sheet1.png
images/formatos-sheet0.png
images/circuborracha-sheet0.png
images/quadborracha-sheet0.png
images/tutpincel-sheet0.png
images/tutborracha-sheet0.png
images/tutcores-sheet0.png
images/tutmover-sheet0.png
images/botaoplay-sheet0.png
images/fundopin-sheet0.png
images/centralizar-sheet0.png
images/centralizar-sheet1.png
images/download-sheet0.png
images/download-sheet1.png
images/fundocompartilhar-sheet0.png
images/linkinsta-sheet0.png
images/linkinsta-sheet1.png
images/fotoinsta-sheet0.png
images/fecharpint-sheet0.png
images/navegação-sheet0.png
images/navegação-sheet1.png
images/telainicial-sheet0.png
images/telatutorial-sheet0.png
images/telaseleção-sheet0.png
images/fechanav-sheet0.png
images/telapintura-sheet0.png
images/sprite-sheet0.png
images/sprite-sheet1.png
images/sprite-sheet2.png
images/sprite-sheet3.png
images/sprite2-sheet0.png
images/fundopronto-sheet0.png
images/preto-sheet0.png
images/vermelho-sheet0.png
images/azul-sheet0.png
images/amarelo-sheet0.png
images/verde-sheet0.png
images/rosa-sheet0.png
images/laranja-sheet0.png
images/roxo-sheet0.png
images/turquesa-sheet0.png
images/fundogaleria-sheet0.png
images/vdesenho-sheet0.png
images/vpreto-sheet0.png
images/voriginal-sheet0.png
images/sprite3-sheet0.png
images/continuar-sheet0.png
icon-16.png
icon-32.png
icon-114.png
icon-128.png
icon-256.png
loading-logo.png
zlib_and_gzip.min.js
NETWORK:
*
